services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: src.backend.app.app:app
      FLASK_ENV: development
    env_file:
      - .env
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

